### PR TITLE
New .env configs and possibly some bugs fixed

### PR DESCRIPTION
**Pull request by ThaMunsta**
- Added max activity config in the .env file!
- Bug fix with finding spaces in hotspot names - looks like you have your own branch refactoring this so ignore anything I'm duplicating
- The `if undefined` logic was flipped but that doesn't seem to work right for me. When it's not undefined we should have a payload to work with?

### CODE REVIEW

**Comment by jamiew** [comment]
Nice patches. PR got a little wonky since I think you branched from your original branch; are you comfortable either trying full rebase (might be messy) or making a fresh branch and cherry-picking your new commits? I usually just do the latter since I hate messy rebases

**Comment by ThaMunsta** [comment]
My bad! Double check I didn't clobber anything you added but I think I resolved the conflicts.

**Comment by jamiew** [comment]
Lgtm! Thanks for the cleanup

**Comment by jamiew** [comment]
Arg handling is kind of goofy; maybe it's OK to just ask everyone to use `magic-animal-names` with dashes? Certainly easier to support. I was using like "hotspot add \"large blue ostrich\"" with quotes but that is weird too

**Comment by jamiew** [comment]
One other ergonomic upgrade would be setting a default MAX if not present. But that only applies to oldies like me with out of date .env's

**Comment by ThaMunsta** [comment]
Yeah I think that's reasonable and would keep it cleaner. I don't like the arg joining but the only alternative I could think of was `args[2] = message.content.replace(/hotspot activity /ig, '').replace(/ /g, '-');` and I can't say I like it any better.
I also agree on the max. I ran into the same thing when moving the code to a "more production" environment and I forgot to update the .env - oops! Good stuff; this has been fun!

**Pull request merged**
